# Generated by Django 4.2.21 on 2025-05-26 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumberType', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Number/Type')),
                ('fullName', models.CharField(max_length=255, verbose_name='Full Name')),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Visit')),
                ('approvedBy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Approved By')),
                ('requestedBy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Requested By')),
                ('requestSource', models.CharField(blank=True, max_length=100, null=True, verbose_name='Request Source')),
                ('checkInTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check-In Time')),
                ('checkOutTime', models.DateTimeField(blank=True, null=True, verbose_name='Check-Out Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Record',
                'verbose_name_plural': 'Visitor Records',
                'ordering': ['-checkInTime'],
            },
        ),
    ]
