# Generated by Django 4.2.21 on 2025-06-13 11:54

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Full Name')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('imageFile', models.ImageField(upload_to=images.models.image_upload_path, verbose_name='Image File')),
                ('idType', models.CharField(choices=[('Visitor', 'Visitor'), ('Staff', 'Staff'), ('Contractor', 'Contractor'), ('Other', 'Other')], default='Visitor', max_length=50, verbose_name='ID Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stored Image (User Registration)',
                'verbose_name_plural': 'Stored Images (User Registrations)',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
