# Generated by Django 4.2.21 on 2025-05-26 12:00

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Full Name of Person in Image')),
                ('imageFile', models.ImageField(upload_to=images.models.image_upload_path, verbose_name='Image File')),
                ('idType', models.CharField(choices=[('Visitor', 'Visitor'), ('Staff', 'Staff'), ('Contractor', 'Contractor'), ('Other', 'Other')], default='Visitor', max_length=50, verbose_name='ID Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stored Image',
                'verbose_name_plural': 'Stored Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
