# Generated by Django 4.2.21 on 2025-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Stored Image (User Registration)', 'verbose_name_plural': 'Stored Images (User Registrations)'},
        ),
        migrations.AddField(
            model_name='storedimage',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='storedimage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='storedimage',
            name='fullName',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
    ]
