# Generated by Django 4.2.21 on 2025-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField()),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('rack_number', models.CharField(max_length=100)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('encoded_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-job_date', '-created_at'],
            },
        ),
    ]
