# Generated by Django 4.2.21 on 2025-06-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by_email',
            field=models.EmailField(blank=True, editable=False, help_text='Email of the user who created this task.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_name',
            field=models.CharField(blank=True, editable=False, help_text='Full name of the user who created this task.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='locations.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact number for the task (can be auto-filled)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='encoded_by',
            field=models.CharField(help_text='Name of the user who encoded/entered the task details', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='full_name',
            field=models.CharField(help_text="Client or contact person's full name for the task", max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='job_id',
            field=models.CharField(editable=False, help_text='Auto-generated Job ID (e.g., LOC-0001)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('location', 'job_id')},
        ),
    ]
