# Generated by Django 4.2.21 on 2025-06-15 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStorageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Times Global', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('office_address', models.CharField(default='Main Office Address', max_length=500)),
                ('submitter_name', models.CharField(max_length=255)),
                ('submitter_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submitter_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('submitter_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('submitter_signature', models.CharField(help_text='Typed name as signature', max_length=255)),
                ('prepared_by_signature', models.CharField(help_text='Typed name as signature', max_length=255)),
                ('created_by_name', models.CharField(blank=True, editable=False, help_text='Full name of the user who created this entry.', max_length=255, null=True)),
                ('created_by_email', models.EmailField(blank=True, editable=False, help_text='Email of the user who created this entry.', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_storage_entries', to='locations.location')),
            ],
            options={
                'verbose_name': 'Device Storage Entry',
                'verbose_name_plural': 'Device Storage Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient Name (MR/MRS.)')),
                ('recipient_address', models.TextField(blank=True, null=True, verbose_name='Recipient Address')),
                ('prepared_by', models.CharField(max_length=255, verbose_name='Prepared By')),
                ('received_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Received By')),
                ('approved_by', models.CharField(max_length=255, verbose_name='Approved By')),
                ('pass_date', models.DateField()),
                ('created_by_name', models.CharField(blank=True, editable=False, help_text='Full name of the user who created this pass.', max_length=255, null=True)),
                ('created_by_email', models.EmailField(blank=True, editable=False, help_text='Email of the user who created this pass.', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes', to='locations.location')),
            ],
            options={
                'verbose_name': 'Gate Pass',
                'verbose_name_plural': 'Gate Passes',
                'ordering': ['-pass_date'],
            },
        ),
        migrations.CreateModel(
            name='GatePassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, max_length=50, null=True, verbose_name='S.No.')),
                ('itemName', models.CharField(max_length=255, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forms_module.gatepass')),
            ],
            options={
                'verbose_name': 'Gate Pass Item',
                'verbose_name_plural': 'Gate Pass Items',
            },
        ),
        migrations.CreateModel(
            name='DeviceStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, max_length=50, null=True, verbose_name='S.No.')),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=500, verbose_name='Item Description')),
                ('rackNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rack No.')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forms_module.devicestorageentry')),
            ],
            options={
                'verbose_name': 'Device Storage Item',
                'verbose_name_plural': 'Device Storage Items',
            },
        ),
    ]
