# Generated by Django 4.2.21 on 2025-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized_locations',
            field=models.ManyToManyField(blank=True, help_text='Locations this user is authorized to access data for.', related_name='authorized_users', to='locations.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False, help_text="Designates whether the user's dashboard access is approved by an admin."),
        ),
    ]
